import {currentAccess,canAccessOrganization,type Access} from "@/lib/access";
import {asMinutes,database,formatTime,id,inTimezone,normalizePhone,now,resolveSchedule,seedDemoData,sha256,staffCanServe,validDate} from "@/lib/booking";
import {notifyPartner,telegramConfigured} from "@/lib/telegram";
import {BloomClubVerificationError,bloomClubConfigured,notifyBloomClub,type BloomClubBookingEvent,verifyBloomClubMember} from "@/lib/bloom-club";
import {hashPassword,validPassword} from "@/lib/password";

type Dict=Record<string,any>;
const publicOrganizationFields="o.id,o.slug,o.name,o.city,o.address,o.category,o.description,o.phone,o.color,o.bloom_discount_percent,o.timezone,o.booking_lead_minutes,o.slot_step_minutes";
function fail(message:string,status=400){return Response.json({error:message},{status})}
function validTime(time:string){return /^([01]\d|2[0-3]):[0-5]\d$/.test(time)}

async function notifyClubAboutBooking(appointmentId:string,eventType:BloomClubBookingEvent["eventType"]){
 const appointment=await database().prepare("SELECT id,club_member_id,club_partner_id,appointment_date,appointment_time,price,discount_amount FROM appointments WHERE id=? AND club_member_id>0 AND club_partner_id>0").bind(appointmentId).first<Dict>();
 if(!appointment)return false;
 return notifyBloomClub({eventType,bookingId:appointment.id,memberId:Number(appointment.club_member_id),partnerId:Number(appointment.club_partner_id),appointmentDate:appointment.appointment_date,appointmentTime:appointment.appointment_time,price:Number(appointment.price),discount:Number(appointment.discount_amount)});
}

async function availableSlots(staffId:string,serviceId:string,date:string,ignoreId=""){
 const db=database(),member=await db.prepare("SELECT s.*,o.timezone,o.booking_lead_minutes,o.slot_step_minutes FROM staff s JOIN organizations o ON o.id=s.organization_id WHERE s.id=? AND s.active=1 AND o.active=1").bind(staffId).first<Dict>(),service=await db.prepare("SELECT * FROM services WHERE id=? AND active=1").bind(serviceId).first<Dict>();
 if(!member||!service||member.organization_id!==service.organization_id||!await staffCanServe(staffId,serviceId))return null;
 const current=inTimezone(member.timezone);if(date<current.date)return{slots:[],member,service};const schedule=await resolveSchedule(member,date);if(!schedule)return{slots:[],member,service};
 const booked=await db.prepare("SELECT id,appointment_time,duration FROM appointments WHERE staff_id=? AND appointment_date=? AND status!='cancelled'").bind(staffId,date).all<Dict>(),slots:string[]=[],step=Math.max(15,Number(member.slot_step_minutes??30)),buffer=Math.max(0,Number(member.buffer_minutes??0));
 for(let minute=asMinutes(schedule.start);minute+Number(service.duration)<=asMinutes(schedule.end);minute+=step){
  const end=minute+Number(service.duration);if(date===current.date&&minute<current.minutes+Number(member.booking_lead_minutes??60))continue;
  if(member.break_start&&member.break_end&&minute<asMinutes(member.break_end)&&end>asMinutes(member.break_start))continue;
  if(booked.results.some(item=>item.id!==ignoreId&&minute<asMinutes(item.appointment_time)+Number(item.duration)+buffer&&end+buffer>asMinutes(item.appointment_time)))continue;
  slots.push(formatTime(minute));
 }
 return{slots,member,service};
}

async function createBooking(payload:Dict,request:Request,access:Access|null){
 const db=database(),name=String(payload.customerName??"").trim(),phone=normalizePhone(String(payload.customerPhone??"")),date=String(payload.date??""),time=String(payload.time??"");
 if(name.length<2||name.length>100||phone.length<10||phone.length>15||!validDate(date)||!validTime(time))return fail("Проверьте имя, номер телефона, дату и время.");
 if(!access&&String(payload.website??"").trim())return fail("Не удалось обработать запись.");
 const availability=await availableSlots(String(payload.staffId??""),String(payload.serviceId??""),date);if(!availability)return fail("Выбранные мастер и услуга несовместимы.");const{member,service,slots}=availability;
 if(access&&!canAccessOrganization(access,member.organization_id))return fail("Вы не можете создавать записи другому партнёру.",403);if(!slots.includes(time))return fail("Выбранное время недоступно или уже прошло.",409);
 const blocked=await db.prepare("SELECT blocked FROM customer_notes WHERE organization_id=? AND phone=?").bind(member.organization_id,phone).first<{blocked:number}>();if(blocked?.blocked&&!access)return fail("Онлайн-запись недоступна. Свяжитесь с администратором.",403);
 if(!access){
  const address=request.headers.get("cf-connecting-ip")??request.headers.get("x-real-ip")??"unknown",fingerprint=await sha256(`${phone}:${address}`),threshold=new Date(Date.now()-15*60_000).toISOString(),attempts=await db.prepare("SELECT COUNT(*) AS count FROM booking_attempts WHERE fingerprint=? AND created_at>?").bind(fingerprint,threshold).first<{count:number}>();if(Number(attempts?.count??0)>=5)return fail("Слишком много попыток записи. Попробуйте через 15 минут.",429);await db.prepare("INSERT INTO booking_attempts (id,fingerprint,created_at) VALUES (?,?,?)").bind(id("att"),fingerprint,now()).run();
 }
 const source=access?"manual":String(payload.source??"direct")==="bloom-club"?"bloom-club":"direct",clubToken=String(payload.clubToken??""),organization=await db.prepare("SELECT bloom_discount_percent,slug FROM organizations WHERE id=?").bind(member.organization_id).first<{bloom_discount_percent:number;slug:string}>();
 let verifiedClubMember=false,clubMemberId=0,clubPartnerId=0;
 if(!access&&source==="bloom-club"&&clubToken){
  try{
   const membership=await verifyBloomClubMember(clubToken,organization?.slug);
   if(membership.phone&&normalizePhone(membership.phone)!==phone)return fail("Номер телефона не совпадает с профилем Bloom Club.",403);
   verifiedClubMember=membership.active;
   if(verifiedClubMember){clubMemberId=membership.memberId;clubPartnerId=membership.partnerId}
  }catch(error){
   if(error instanceof BloomClubVerificationError)return fail(error.message,error.status);
   return fail("Не удалось подтвердить участие в Bloom Club.",503);
  }
 }
 const discount=verifiedClubMember?Math.floor(Number(service.price)*Number(organization?.bloom_discount_percent??0)/100):0,price=Number(service.price)-discount,bookingId=id("apt"),token=crypto.randomUUID(),created=now(),start=asMinutes(time),end=start+Number(service.duration),buffer=Number(member.buffer_minutes??0);
 const result=await db.prepare("INSERT INTO appointments (id,organization_id,staff_id,service_id,customer_name,customer_phone,appointment_date,appointment_time,duration,price,original_price,discount_amount,club_member_id,club_partner_id,public_token,status,source,notes,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'confirmed',?,?,? WHERE NOT EXISTS (SELECT 1 FROM appointments WHERE staff_id=? AND appointment_date=? AND status!='cancelled' AND (CAST(substr(appointment_time,1,2) AS INTEGER)*60+CAST(substr(appointment_time,4,2) AS INTEGER))<? AND (CAST(substr(appointment_time,1,2) AS INTEGER)*60+CAST(substr(appointment_time,4,2) AS INTEGER)+duration+?)>?)").bind(bookingId,member.organization_id,member.id,service.id,name,phone,date,time,service.duration,price,service.price,discount,clubMemberId,clubPartnerId,token,source,String(payload.notes??"").slice(0,1000),created,member.id,date,end+buffer,buffer,start).run();if(!result.meta?.changes)return fail("Это время только что заняли. Выберите другой интервал.",409);
 try{await notifyPartner(member.organization_id,bookingId,"new_booking")}catch{}
 try{await notifyClubAboutBooking(bookingId,"booking_created")}catch{}
 return Response.json({success:true,id:bookingId,token,price,originalPrice:service.price,discount},{status:201});
}

export async function GET(request:Request){
 try{
  await seedDemoData();const db=database(),url=new URL(request.url),kind=url.searchParams.get("kind")??"organizations";
  if(kind==="organizations"){const{results}=await db.prepare(`SELECT ${publicOrganizationFields},(SELECT COUNT(*) FROM staff s WHERE s.organization_id=o.id AND s.active=1) AS staff_count,(SELECT MIN(price) FROM services v WHERE v.organization_id=o.id AND v.active=1) AS min_price FROM organizations o WHERE o.active=1 ORDER BY o.created_at,o.name`).all();return Response.json({organizations:results})}
  if(kind==="organization"){
   const slug=url.searchParams.get("slug");if(!slug)return fail("Не указан партнёр.");const organization=await db.prepare(`SELECT ${publicOrganizationFields} FROM organizations o WHERE o.slug=? AND o.active=1`).bind(slug).first<Dict>();if(!organization)return fail("Партнёр не найден.",404);
   const members=await db.prepare("SELECT id,organization_id,name,role,work_start,work_end FROM staff WHERE organization_id=? AND active=1 ORDER BY name").bind(organization.id).all(),offerings=await db.prepare("SELECT id,organization_id,name,price,duration FROM services WHERE organization_id=? AND active=1 ORDER BY price").bind(organization.id).all(),links=await db.prepare("SELECT staff_id,service_id FROM staff_services WHERE organization_id=?").bind(organization.id).all();return Response.json({organization,staff:members.results,services:offerings.results,staffServices:links.results});
  }
  if(kind==="slots"){const staffId=url.searchParams.get("staffId"),serviceId=url.searchParams.get("serviceId"),date=url.searchParams.get("date");if(!staffId||!serviceId||!date||!validDate(date))return fail("Выберите мастера, услугу и дату.");const availability=await availableSlots(staffId,serviceId,date);if(!availability)return fail("Мастер или услуга недоступны.",404);return Response.json({slots:availability.slots})}
  if(kind==="appointment"){
   const appointmentId=url.searchParams.get("id"),token=url.searchParams.get("token");if(!appointmentId||!token)return fail("Не указана запись.");const item=await db.prepare("SELECT a.id,a.appointment_date,a.appointment_time,a.price,a.original_price,a.discount_amount,a.status,a.public_token,o.name AS organization_name,o.address,o.city,s.name AS staff_name,v.name AS service_name FROM appointments a JOIN organizations o ON o.id=a.organization_id JOIN staff s ON s.id=a.staff_id JOIN services v ON v.id=a.service_id WHERE a.id=? AND a.public_token=?").bind(appointmentId,token).first<Dict>();if(!item)return fail("Запись не найдена.",404);delete item.public_token;return Response.json({appointment:item});
  }
  if(kind==="dashboard"){
   const access=await currentAccess();if(!access)return fail("Доступ в кабинет не предоставлен. Обратитесь к владельцу сервиса.",403);const requested=url.searchParams.get("organizationId");if(requested&&!canAccessOrganization(access,requested))return fail("У вас нет доступа к этому партнёру.",403);const organizationId=access.role==="partner"?access.organizationId:requested;if(access.role==="partner"&&!organizationId)return fail("Ваш аккаунт не привязан к партнёру.",403);
   const orgs=organizationId?await db.prepare("SELECT * FROM organizations WHERE id=? ORDER BY created_at").bind(organizationId).all<Dict>():await db.prepare("SELECT * FROM organizations ORDER BY active DESC,created_at").all<Dict>(),filter=organizationId?" WHERE a.organization_id=?":"";let query=db.prepare(`SELECT a.*,o.name AS organization_name,s.name AS staff_name,v.name AS service_name FROM appointments a JOIN organizations o ON o.id=a.organization_id JOIN staff s ON s.id=a.staff_id JOIN services v ON v.id=a.service_id${filter} ORDER BY a.appointment_date DESC,a.appointment_time DESC LIMIT 500`);if(organizationId)query=query.bind(organizationId);const bookings=await query.all<Dict>();
   const members=organizationId?await db.prepare("SELECT * FROM staff WHERE organization_id=? ORDER BY active DESC,name").bind(organizationId).all<Dict>():await db.prepare("SELECT * FROM staff ORDER BY active DESC,name").all<Dict>(),offerings=organizationId?await db.prepare("SELECT * FROM services WHERE organization_id=? ORDER BY active DESC,name").bind(organizationId).all<Dict>():await db.prepare("SELECT * FROM services ORDER BY active DESC,name").all<Dict>(),links=organizationId?await db.prepare("SELECT * FROM staff_services WHERE organization_id=?").bind(organizationId).all<Dict>():await db.prepare("SELECT * FROM staff_services").all<Dict>(),exceptions=organizationId?await db.prepare("SELECT e.*,s.name AS staff_name FROM schedule_exceptions e JOIN staff s ON s.id=e.staff_id WHERE e.organization_id=? ORDER BY e.exception_date DESC LIMIT 100").bind(organizationId).all<Dict>():await db.prepare("SELECT e.*,s.name AS staff_name FROM schedule_exceptions e JOIN staff s ON s.id=e.staff_id ORDER BY e.exception_date DESC LIMIT 100").all<Dict>();
   const users=access.role==="owner"?await db.prepare("SELECT a.*,o.name AS organization_name FROM account_access a LEFT JOIN organizations o ON o.id=a.organization_id ORDER BY a.role DESC,a.created_at").all<Dict>():{results:[]},notifications=organizationId?await db.prepare("SELECT n.*,o.name AS organization_name FROM notification_events n JOIN organizations o ON o.id=n.organization_id WHERE n.organization_id=? ORDER BY n.created_at DESC LIMIT 30").bind(organizationId).all<Dict>():access.role==="owner"?await db.prepare("SELECT n.*,o.name AS organization_name FROM notification_events n JOIN organizations o ON o.id=n.organization_id ORDER BY n.created_at DESC LIMIT 30").all<Dict>():{results:[]};
   const customerFilter=organizationId?"WHERE a.organization_id=?":"",customerQuery=db.prepare(`SELECT a.organization_id,a.customer_phone,MAX(a.customer_name) AS customer_name,o.name AS organization_name,COUNT(*) AS visits,SUM(CASE WHEN a.status='completed' THEN 1 ELSE 0 END) AS completed,SUM(CASE WHEN a.status='cancelled' THEN 1 ELSE 0 END) AS cancelled,SUM(CASE WHEN a.status='no_show' THEN 1 ELSE 0 END) AS no_shows,SUM(CASE WHEN a.status!='cancelled' THEN a.price ELSE 0 END) AS total_spent,MAX(a.appointment_date) AS last_visit,COALESCE(n.note,'') AS note,COALESCE(n.blocked,0) AS blocked FROM appointments a JOIN organizations o ON o.id=a.organization_id LEFT JOIN customer_notes n ON n.organization_id=a.organization_id AND n.phone=a.customer_phone ${customerFilter} GROUP BY a.organization_id,a.customer_phone ORDER BY last_visit DESC LIMIT 300`),customers=organizationId?await customerQuery.bind(organizationId).all<Dict>():await customerQuery.all<Dict>();
   return Response.json({organizations:orgs.results,appointments:bookings.results,staff:members.results,services:offerings.results,staffServices:links.results,scheduleExceptions:exceptions.results,customers:customers.results,accounts:users.results,notifications:notifications.results,telegramConfigured:telegramConfigured(),bloomClubConfigured:bloomClubConfigured(),user:{name:access.name,email:access.email,role:access.role,organizationId:access.organizationId}});
  }
  return fail("Неизвестный запрос.",404);
 }catch(error){return fail(error instanceof Error?error.message:"Ошибка сервера.",500)}
}

export async function POST(request:Request){
 try{
  await seedDemoData();const db=database(),payload=await request.json() as Dict,action=String(payload.action??"book");if(action==="book")return createBooking(payload,request,null);
  if(action==="cancel-public"){const appointment=await db.prepare("SELECT id,organization_id,status FROM appointments WHERE id=? AND public_token=? AND public_token!=''").bind(String(payload.id??""),String(payload.token??"")).first<Dict>();if(!appointment)return fail("Запись не найдена.",404);if(appointment.status!=="confirmed")return fail("Эту запись уже нельзя отменить.");await db.prepare("UPDATE appointments SET status='cancelled' WHERE id=?").bind(appointment.id).run();try{await notifyPartner(appointment.organization_id,appointment.id,"cancelled")}catch{}try{await notifyClubAboutBooking(appointment.id,"booking_cancelled")}catch{}return Response.json({success:true})}
  const access=await currentAccess();if(!access)return fail("Доступ в кабинет не предоставлен.",403);if(action==="create-manual")return createBooking(payload,request,access);
  if(action==="update-status"){if(!["confirmed","completed","cancelled","no_show"].includes(String(payload.status)))return fail("Недопустимый статус.");const item=await db.prepare("SELECT id,organization_id FROM appointments WHERE id=?").bind(String(payload.id??"")).first<Dict>();if(!item)return fail("Запись не найдена.",404);if(!canAccessOrganization(access,item.organization_id))return fail("Вы не можете изменять записи другого партнёра.",403);await db.prepare("UPDATE appointments SET status=? WHERE id=? AND organization_id=?").bind(payload.status,item.id,item.organization_id).run();try{await notifyPartner(item.organization_id,item.id,payload.status==="cancelled"?"cancelled":"status_changed")}catch{}if(payload.status!=="confirmed"){const eventType=payload.status==="cancelled"?"booking_cancelled":payload.status==="completed"?"booking_completed":"booking_no_show";try{await notifyClubAboutBooking(item.id,eventType)}catch{}}return Response.json({success:true})}
  if(action==="reschedule"){
   const item=await db.prepare("SELECT * FROM appointments WHERE id=? AND status='confirmed'").bind(String(payload.id??"")).first<Dict>();if(!item)return fail("Подтверждённая запись не найдена.",404);if(!canAccessOrganization(access,item.organization_id))return fail("Вы не можете переносить записи другого партнёра.",403);const date=String(payload.date??""),time=String(payload.time??""),staffId=String(payload.staffId??item.staff_id);if(!validDate(date)||!validTime(time))return fail("Проверьте дату и время переноса.");const availability=await availableSlots(staffId,item.service_id,date,item.id);if(!availability||!availability.slots.includes(time))return fail("Выбранный интервал недоступен.",409);const start=asMinutes(time),end=start+Number(item.duration),buffer=Number(availability.member.buffer_minutes??0);const result=await db.prepare("UPDATE appointments SET staff_id=?,appointment_date=?,appointment_time=? WHERE id=? AND organization_id=? AND NOT EXISTS (SELECT 1 FROM appointments other WHERE other.id!=? AND other.staff_id=? AND other.appointment_date=? AND other.status!='cancelled' AND (CAST(substr(other.appointment_time,1,2) AS INTEGER)*60+CAST(substr(other.appointment_time,4,2) AS INTEGER))<? AND (CAST(substr(other.appointment_time,1,2) AS INTEGER)*60+CAST(substr(other.appointment_time,4,2) AS INTEGER)+other.duration+?)>?)").bind(staffId,date,time,item.id,item.organization_id,item.id,staffId,date,end+buffer,buffer,start).run();if(!result.meta?.changes)return fail("Это время только что заняли.",409);try{await notifyPartner(item.organization_id,item.id,"status_changed")}catch{}try{await notifyClubAboutBooking(item.id,"booking_rescheduled")}catch{}return Response.json({success:true});
  }
  if(action==="add-organization"||action==="edit-organization"){
   if(action==="add-organization"&&access.role!=="owner")return fail("Только владелец может добавлять партнёров.",403);const name=String(payload.name??"").trim(),slug=String(payload.slug??"").trim().toLowerCase();if(name.length<2||!/^[-a-z0-9]{3,50}$/.test(slug))return fail("Укажите название и адрес страницы латиницей.");if(action==="add-organization"){await db.prepare("INSERT INTO organizations (id,slug,name,city,address,category,description,phone,color,active,created_at) VALUES (?,?,?,?,?,?,?,?,?,1,?)").bind(id("org"),slug,name,String(payload.city??"Новосибирск"),String(payload.address??""),String(payload.category??"Красота и уход"),String(payload.description??""),String(payload.phone??""),"#f6e7e2",now()).run();return Response.json({success:true},{status:201})}const organizationId=String(payload.organizationId??"");if(!canAccessOrganization(access,organizationId))return fail("У вас нет доступа к этому партнёру.",403);await db.prepare("UPDATE organizations SET slug=?,name=?,city=?,address=?,category=?,description=?,phone=? WHERE id=?").bind(slug,name,String(payload.city??""),String(payload.address??""),String(payload.category??""),String(payload.description??""),String(payload.phone??""),organizationId).run();return Response.json({success:true});
  }
  if(action==="add-staff"||action==="edit-staff"){
   const name=String(payload.name??"").trim(),organizationId=String(payload.organizationId??"");if(name.length<2||!organizationId)return fail("Укажите партнёра и имя специалиста.");if(!canAccessOrganization(access,organizationId))return fail("Вы не можете изменять специалистов другого партнёра.",403);const workStart=String(payload.workStart??"10:00"),workEnd=String(payload.workEnd??"19:00"),breakStart=String(payload.breakStart??""),breakEnd=String(payload.breakEnd??""),buffer=Number(payload.bufferMinutes??0),days=(Array.isArray(payload.workDays)?payload.workDays:String(payload.workDays??"1,2,3,4,5,6").split(",")).map(Number).filter(value=>Number.isInteger(value)&&value>=1&&value<=7);if(!validTime(workStart)||!validTime(workEnd)||asMinutes(workStart)>=asMinutes(workEnd)||!days.length||!Number.isInteger(buffer)||buffer<0||buffer>120)return fail("Проверьте рабочий график специалиста.");if((breakStart||breakEnd)&&(!validTime(breakStart)||!validTime(breakEnd)||asMinutes(breakStart)>=asMinutes(breakEnd)))return fail("Проверьте время перерыва.");let staffId=String(payload.id??"");if(action==="add-staff"){staffId=id("st");await db.prepare("INSERT INTO staff (id,organization_id,name,role,active,work_start,work_end,work_days,break_start,break_end,buffer_minutes,created_at) VALUES (?,?,?,?,1,?,?,?,?,?,?,?)").bind(staffId,organizationId,name,String(payload.role??"Специалист"),workStart,workEnd,days.join(","),breakStart,breakEnd,buffer,now()).run()}else{const item=await db.prepare("SELECT id FROM staff WHERE id=? AND organization_id=?").bind(staffId,organizationId).first();if(!item)return fail("Специалист не найден.",404);await db.prepare("UPDATE staff SET name=?,role=?,work_start=?,work_end=?,work_days=?,break_start=?,break_end=?,buffer_minutes=? WHERE id=? AND organization_id=?").bind(name,String(payload.role??"Специалист"),workStart,workEnd,days.join(","),breakStart,breakEnd,buffer,staffId,organizationId).run()}
   if(Array.isArray(payload.serviceIds)){const ids=Array.from(new Set(payload.serviceIds.map(String)));for(const serviceId of ids){const service=await db.prepare("SELECT id FROM services WHERE id=? AND organization_id=?").bind(serviceId,organizationId).first();if(!service)return fail("Услуга не принадлежит выбранному партнёру.")}await db.batch([db.prepare("DELETE FROM staff_services WHERE staff_id=? AND organization_id=?").bind(staffId,organizationId),...ids.map(serviceId=>db.prepare("INSERT INTO staff_services (id,staff_id,service_id,organization_id) VALUES (?,?,?,?)").bind(id("ss"),staffId,serviceId,organizationId))])}return Response.json({success:true},{status:action==="add-staff"?201:200});
  }
  if(action==="add-service"||action==="edit-service"){
   const name=String(payload.name??"").trim(),organizationId=String(payload.organizationId??""),price=Number(payload.price),duration=Number(payload.duration);if(name.length<2||!organizationId||!Number.isInteger(price)||price<0||!Number.isInteger(duration)||duration<15||duration>720)return fail("Проверьте название, стоимость и длительность услуги.");if(!canAccessOrganization(access,organizationId))return fail("Вы не можете изменять услуги другого партнёра.",403);if(action==="add-service"){await db.prepare("INSERT INTO services (id,organization_id,name,price,duration,active,created_at) VALUES (?,?,?,?,?,1,?)").bind(id("sv"),organizationId,name,price,duration,now()).run();return Response.json({success:true},{status:201})}await db.prepare("UPDATE services SET name=?,price=?,duration=? WHERE id=? AND organization_id=?").bind(name,price,duration,String(payload.id??""),organizationId).run();return Response.json({success:true});
  }
  if(action==="toggle-entity"){
   const type=String(payload.type??""),entityId=String(payload.id??"");if(!["organization","staff","service"].includes(type))return fail("Неизвестный объект.");const table=type==="organization"?"organizations":type==="staff"?"staff":"services",item=await db.prepare(`SELECT id,${type==="organization"?"id":"organization_id"} AS organization_id FROM ${table} WHERE id=?`).bind(entityId).first<Dict>();if(!item)return fail("Объект не найден.",404);if(type==="organization"&&access.role!=="owner")return fail("Только владелец может отключать партнёров.",403);if(!canAccessOrganization(access,item.organization_id))return fail("У вас нет доступа к этому объекту.",403);await db.prepare(`UPDATE ${table} SET active=? WHERE id=?`).bind(payload.active?1:0,entityId).run();return Response.json({success:true});
  }
  if(action==="save-exception"){
   const staffId=String(payload.staffId??""),date=String(payload.date??""),member=await db.prepare("SELECT id,organization_id FROM staff WHERE id=?").bind(staffId).first<Dict>();if(!member||!canAccessOrganization(access,member.organization_id))return fail("Специалист недоступен.",403);if(!validDate(date))return fail("Проверьте дату.");const isDayOff=payload.isDayOff?1:0,start=String(payload.workStart??""),end=String(payload.workEnd??"");if(!isDayOff&&(!validTime(start)||!validTime(end)||asMinutes(start)>=asMinutes(end)))return fail("Укажите рабочее время.");await db.prepare("INSERT INTO schedule_exceptions (id,staff_id,organization_id,exception_date,is_day_off,work_start,work_end,note) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(staff_id,exception_date) DO UPDATE SET is_day_off=excluded.is_day_off,work_start=excluded.work_start,work_end=excluded.work_end,note=excluded.note").bind(id("exc"),staffId,member.organization_id,date,isDayOff,start,end,String(payload.note??"")).run();return Response.json({success:true});
  }
  if(action==="remove-exception"){const item=await db.prepare("SELECT id,organization_id FROM schedule_exceptions WHERE id=?").bind(String(payload.id??"")).first<Dict>();if(!item||!canAccessOrganization(access,item.organization_id))return fail("Исключение недоступно.",403);await db.prepare("DELETE FROM schedule_exceptions WHERE id=? AND organization_id=?").bind(item.id,item.organization_id).run();return Response.json({success:true})}
  if(action==="save-customer"){
   const organizationId=String(payload.organizationId??""),phone=normalizePhone(String(payload.phone??""));if(!canAccessOrganization(access,organizationId))return fail("У вас нет доступа к клиентам этого партнёра.",403);if(phone.length<10)return fail("Проверьте номер клиента.");await db.prepare("INSERT INTO customer_notes (id,organization_id,phone,note,blocked,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(organization_id,phone) DO UPDATE SET note=excluded.note,blocked=excluded.blocked,updated_at=excluded.updated_at").bind(id("cus"),organizationId,phone,String(payload.note??"").slice(0,2000),payload.blocked?1:0,now()).run();return Response.json({success:true});
  }
  if(action==="add-account"){if(access.role!=="owner")return fail("Только владелец управляет доступами.",403);const email=String(payload.email??"").trim().toLowerCase(),organizationId=String(payload.organizationId??""),password=String(payload.password??"");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!organizationId)return fail("Укажите корректный email и партнёра.");if(!validPassword(password))return fail("Пароль должен содержать от 12 до 128 символов.");const organization=await db.prepare("SELECT id FROM organizations WHERE id=?").bind(organizationId).first();if(!organization)return fail("Партнёр не найден.",404);await db.prepare("INSERT INTO account_access (id,email,display_name,role,organization_id,password_hash,active,created_at) VALUES (?,?,?,'partner',?,?,1,?)").bind(id("acc"),email,String(payload.displayName??""),organizationId,await hashPassword(password),now()).run();return Response.json({success:true},{status:201})}
  if(action==="update-account"){if(access.role!=="owner")return fail("Только владелец управляет доступами.",403);const record=await db.prepare("SELECT id,role FROM account_access WHERE id=?").bind(String(payload.id??"")).first<Dict>();if(!record)return fail("Пользователь не найден.",404);if(record.role==="owner")return fail("Нельзя отключить владельца.");await db.prepare("UPDATE account_access SET active=? WHERE id=? AND role='partner'").bind(payload.active?1:0,record.id).run();return Response.json({success:true})}
  if(action==="update-organization"){
   const organizationId=String(payload.organizationId??"");if(!organizationId||!canAccessOrganization(access,organizationId))return fail("У вас нет доступа к настройкам этого партнёра.",403);const chatId=String(payload.telegramChatId??"").trim(),discount=Number(payload.bloomDiscountPercent??0),timezone=String(payload.timezone??"Asia/Novosibirsk"),lead=Number(payload.bookingLeadMinutes??60),step=Number(payload.slotStepMinutes??30);if(chatId&&!/^-?\d{5,20}$/.test(chatId))return fail("Telegram chat ID должен содержать только цифры.");if(!Number.isInteger(discount)||discount<0||discount>90)return fail("Скидка должна быть от 0 до 90%.");if(!["Asia/Novosibirsk","Europe/Moscow","Asia/Yekaterinburg"].includes(timezone))return fail("Выберите часовой пояс из списка.");if(!Number.isInteger(lead)||lead<0||lead>10080||![15,30,60].includes(step))return fail("Проверьте настройки интервалов записи.");await db.prepare("UPDATE organizations SET telegram_chat_id=?,notifications_enabled=?,bloom_discount_percent=?,timezone=?,booking_lead_minutes=?,slot_step_minutes=? WHERE id=?").bind(chatId,payload.notificationsEnabled?1:0,discount,timezone,lead,step,organizationId).run();return Response.json({success:true});
  }
  if(action==="test-telegram"){const organizationId=String(payload.organizationId??"");if(!canAccessOrganization(access,organizationId))return fail("У вас нет доступа к настройкам этого партнёра.",403);const result=await notifyPartner(organizationId,null,"test","🌸 <b>Bloom Online</b>\n\nТестовое уведомление: Telegram успешно подключён.");if(!result.sent)return fail(result.reason);return Response.json({success:true})}
  return fail("Неизвестное действие.");
 }catch(error){const message=error instanceof Error?error.message:"Ошибка сервера.";return fail(message.includes("UNIQUE")?"Такое значение уже существует или время уже занято.":message,message.includes("UNIQUE")?409:500)}
}
