"use client";
import {FormEvent,useState} from "react";
import Link from "next/link";
import BrandLogo from "@/app/components/brand-logo";

export default function LoginPage(){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[city,setCity]=useState(""),[registering,setRegistering]=useState(false),[offerAccepted,setOfferAccepted]=useState(false),[personalDataConsent,setPersonalDataConsent]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const returnTo=new URLSearchParams(window.location.search).get("return_to"),response=await fetch(registering?"/api/auth/register":"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,name,city,returnTo,offerAccepted,personalDataConsent})}),result=await response.json();if(!response.ok)throw Error(result.error);window.location.href=result.returnTo}catch(reason){setError(reason instanceof Error?reason.message:registering?"Не удалось зарегистрироваться.":"Не удалось войти.")}finally{setBusy(false)}}
 return <main className="login-page"><form className={`login-card${registering?" registration-card":""}`} onSubmit={submit}><BrandLogo/><div className="eyebrow">BLOOM ONLINE · ДЛЯ БИЗНЕСА</div><h1>{registering?"Регистрация салона":"Личный кабинет"}</h1><p>{registering?"Создайте кабинет, добавьте сотрудников, услуги и откройте онлайн-запись.":"Управляйте сотрудниками, услугами, графиком работы и записями клиентов."}</p>{registering&&<><label className="field-label">Название салона<input autoComplete="organization" minLength={2} maxLength={100} required value={name} onChange={event=>setName(event.target.value)} placeholder="Например, Bloom Beauty"/></label><label className="field-label">Город<input autoComplete="address-level2" minLength={2} maxLength={100} required value={city} onChange={event=>setCity(event.target.value)} placeholder="Например, Новосибирск"/></label></>}<label className="field-label">Электронная почта<input type="email" autoComplete="email" maxLength={254} required value={email} onChange={event=>setEmail(event.target.value)} placeholder="salon@example.ru"/></label><label className="field-label">Пароль<input type="password" autoComplete={registering?"new-password":"current-password"} minLength={6} maxLength={128} required value={password} onChange={event=>setPassword(event.target.value)} placeholder={registering?"Не менее 6 символов":""}/>{registering&&<small>Не менее 6 символов.</small>}</label>{registering&&<div className="registration-consents"><label className="legal-consent"><input type="checkbox" checked={offerAccepted} onChange={event=>setOfferAccepted(event.target.checked)}/><span>Я принимаю условия <Link href="/offer" target="_blank">публичной оферты</Link> и <Link href="/terms" target="_blank">пользовательского соглашения</Link>.</span></label><label className="legal-consent"><input type="checkbox" checked={personalDataConsent} onChange={event=>setPersonalDataConsent(event.target.checked)}/><span>Я даю <Link href="/personal-data-consent" target="_blank">согласие на обработку персональных данных</Link> и ознакомлен с <Link href="/privacy" target="_blank">политикой конфиденциальности</Link>.</span></label></div>}{error&&<p className="error-text">{error}</p>}<button className="button button-dark button-large" disabled={busy||(registering&&(!offerAccepted||!personalDataConsent))}>{busy?(registering?"Создаём кабинет…":"Входим…"):(registering?"Зарегистрироваться":"Войти")}</button><p className="auth-switch">{registering?"Уже зарегистрированы?":"Ещё не зарегистрированы?"} <button type="button" onClick={()=>{setRegistering(!registering);setError("");setOfferAccepted(false);setPersonalDataConsent(false)}}>{registering?"Войти":"Создать личный кабинет"}</button></p><p className="login-legal-links"><Link href="/offer">Оферта</Link><Link href="/privacy">Конфиденциальность</Link></p></form></main>
}
