"use client";
import Link from "next/link";
import BrandLogo from "@/app/components/brand-logo";
import{useEffect,useState}from"react";
type Dict=Record<string,any>;
const rub=(value:number)=>`${new Intl.NumberFormat("ru-RU").format(value)} ₽`;
export default function ManageAppointment({id}:{id:string}){
 const[item,setItem]=useState<Dict|null>(null),[token,setToken]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const key=new URLSearchParams(window.location.search).get("token")??"";setToken(key);fetch(`/api/booking?kind=appointment&id=${encodeURIComponent(id)}&token=${encodeURIComponent(key)}`).then(async response=>{const result=await response.json();if(!response.ok)throw Error(result.error);setItem(result.appointment)}).catch(reason=>setError(reason.message))},[id]);
 async function cancel(){if(!window.confirm("Отменить запись?"))return;setBusy(true);try{const response=await fetch("/api/booking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"cancel-public",id,token})});const result=await response.json();if(!response.ok)throw Error(result.error);setItem(item?{...item,status:"cancelled"}:null)}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось отменить запись")}finally{setBusy(false)}}
 return<main className="booking-shell confirmation"><BrandLogo />{error?<p className="error-text">{error}</p>:!item?<p className="muted">Загружаем запись…</p>:<><div className={`confirm-icon${item.status==="cancelled"?" confirm-cancelled":""}`}>{item.status==="cancelled"?"×":"✓"}</div><div className="eyebrow">{item.status==="cancelled"?"ЗАПИСЬ ОТМЕНЕНА":"ВАША ЗАПИСЬ"}</div><h1 className="booking-title">{item.organization_name}</h1><div className="summary-box"><div><span>Услуга</span><strong>{item.service_name}</strong></div><div><span>Специалист</span><strong>{item.staff_name}</strong></div><div><span>Дата и время</span><strong>{new Date(`${item.appointment_date}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"long"})}, {item.appointment_time}</strong></div><div><span>Адрес</span><strong>{item.city}, {item.address}</strong></div><div><span>Стоимость</span><strong>{rub(item.price)}</strong></div></div>{item.status==="confirmed"&&<button className="button button-outline button-large manage-link" disabled={busy} onClick={cancel}>{busy?"Отменяем…":"Отменить запись"}</button>}<Link href="/" className="button button-dark button-large">На главную</Link></>}</main>
}
