"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";

type Dict=Record<string,any>;
const rub=(value:number)=>`${new Intl.NumberFormat("ru-RU").format(value)} ₽`;
const statuses:Record<string,string>={confirmed:"Подтверждена",completed:"Завершена",cancelled:"Отменена",no_show:"Неявка"};
const menu=[{id:"overview",label:"Обзор",icon:"◫"},{id:"appointments",label:"Записи",icon:"◷"},{id:"partners",label:"Партнёры",icon:"◉"},{id:"staff",label:"Специалисты",icon:"♧"},{id:"services",label:"Услуги",icon:"✧"}];

export default function Dashboard(){
 const[tab,setTab]=useState("overview"),[data,setData]=useState<Dict|null>(null),[organization,setOrganization]=useState(""),[modal,setModal]=useState(""),[form,setForm]=useState<Dict>({}),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(()=>{fetch(`/api/booking?kind=dashboard${organization?`&organizationId=${encodeURIComponent(organization)}`:""}`).then(async response=>{const result=await response.json();if(!response.ok)throw Error(result.error);setData(result)}).catch(reason=>setError(reason.message))},[organization]);
 useEffect(load,[load]);
 const metrics=useMemo(()=>{const list=data?.appointments??[],active=list.filter((item:Dict)=>item.status!=="cancelled"),today=new Date().toISOString().slice(0,10);return{total:active.length,today:active.filter((item:Dict)=>item.appointment_date===today).length,revenue:active.reduce((sum:number,item:Dict)=>sum+Number(item.price),0),partners:(data?.organizations??[]).length}},[data]);
 async function send(action:string,values:Dict){setBusy(true);setError("");try{const response=await fetch("/api/booking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...values})});const result=await response.json();if(!response.ok)throw Error(result.error);setModal("");setForm({});load()}catch(reason){setError(reason instanceof Error?reason.message:"Ошибка сохранения")}finally{setBusy(false)}}
 function field(key:string,value:any){setForm({...form,[key]:value})}
 const list=data?.appointments??[];
 return <main className="dashboard"><aside className="sidebar"><Link href="/" className="brand"><span className="brand-mark">✿</span> bloom<span>online</span></Link><div className="sidebar-label">УПРАВЛЕНИЕ</div><nav className="side-menu">{menu.map(item=><button onClick={()=>setTab(item.id)} className={tab===item.id?"active":""} key={item.id}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-bottom"><div className="avatar">{data?.user?.name?.[0]??"B"}</div><div><strong>{data?.user?.name??"Владелец"}</strong><span>Администратор</span></div></div></aside><section className="dashboard-main"><header className="dashboard-top"><span className="eyebrow">BLOOM ONLINE / {menu.find(item=>item.id===tab)?.label.toUpperCase()}</span><select value={organization} onChange={event=>setOrganization(event.target.value)}><option value="">Все партнёры</option>{(data?.organizations??[]).map((org:Dict)=><option key={org.id} value={org.id}>{org.name}</option>)}</select></header><div className="dashboard-body">
 {tab==="overview"&&<><div className="dashboard-heading"><div><div className="eyebrow">ДОБРО ПОЖАЛОВАТЬ</div><h1 className="dashboard-title">Обзор</h1></div><button className="button button-dark" onClick={()=>setModal("organization")}>+ Добавить партнёра</button></div><div className="metrics-grid"><Metric label="Все записи" value={String(metrics.total)} hint="За всё время"/><Metric label="Записи сегодня" value={String(metrics.today)} hint="На текущую дату"/><Metric label="Сумма записей" value={rub(metrics.revenue)} hint="Без отменённых"/><Metric label="Партнёры" value={String(metrics.partners)} hint="Подключено к сервису"/></div><div className="block-heading"><h2>Последние записи</h2><button onClick={()=>setTab("appointments")}>Смотреть все →</button></div><AppointmentTable list={list.slice(0,7)} onStatus={(item,status)=>send("update-status",{id:item.id,status})}/></>}
 {tab==="appointments"&&<><div className="dashboard-heading"><div><div className="eyebrow">ЖУРНАЛ ВИЗИТОВ</div><h1 className="dashboard-title">Записи</h1></div><span className="muted">{list.length} всего</span></div><AppointmentTable list={list} onStatus={(item,status)=>send("update-status",{id:item.id,status})}/></>}
 {tab==="partners"&&<><div className="dashboard-heading"><div><div className="eyebrow">ВАША ЭКОСИСТЕМА</div><h1 className="dashboard-title">Партнёры</h1></div><button className="button button-dark" onClick={()=>setModal("organization")}>+ Добавить партнёра</button></div><div className="admin-card-grid">{(data?.organizations??[]).map((org:Dict)=><article className="admin-card" key={org.id}><div className="admin-card-badge" style={{background:org.color}}>{org.name.split(" ").map((word:string)=>word[0]).join("")}</div><h3>{org.name}</h3><p>{org.category} · {org.city}</p><span className="muted">{org.address}</span><Link href={`/book/${org.slug}`} target="_blank">Страница записи ↗</Link></article>)}</div></>}
 {tab==="staff"&&<><div className="dashboard-heading"><div><div className="eyebrow">КОМАНДА ПАРТНЁРОВ</div><h1 className="dashboard-title">Специалисты</h1></div><button className="button button-dark" onClick={()=>{setForm({organizationId:organization||data?.organizations?.[0]?.id,workStart:"10:00",workEnd:"19:00"});setModal("staff")}}>+ Добавить мастера</button></div><div className="admin-card-grid">{(data?.staff??[]).map((item:Dict)=><article className="admin-card staff-card" key={item.id}><div className="avatar avatar-large">{item.name[0]}</div><h3>{item.name}</h3><p>{item.role}</p><span className="muted">{data?.organizations.find((org:Dict)=>org.id===item.organization_id)?.name}</span><div className="staff-hours">◷ {item.work_start} — {item.work_end}</div></article>)}</div></>}
 {tab==="services"&&<><div className="dashboard-heading"><div><div className="eyebrow">ПРАЙС-ЛИСТ</div><h1 className="dashboard-title">Услуги</h1></div><button className="button button-dark" onClick={()=>{setForm({organizationId:organization||data?.organizations?.[0]?.id,duration:60});setModal("service")}}>+ Добавить услугу</button></div><div className="service-table">{(data?.services??[]).map((item:Dict)=><div className="service-row" key={item.id}><div><strong>{item.name}</strong><span>{data?.organizations.find((org:Dict)=>org.id===item.organization_id)?.name}</span></div><span>{item.duration} мин</span><strong>{rub(item.price)}</strong></div>)}</div></>}
 {error&&<p className="error-text">{error}</p>}</div></section>
 {modal&&<div className="modal-backdrop" onClick={event=>{if(event.target===event.currentTarget)setModal("")}}><div className="modal"><button className="modal-close" onClick={()=>setModal("")}>×</button><div className="eyebrow">НОВАЯ ЗАПИСЬ В СИСТЕМЕ</div><h2>{modal==="organization"?"Добавить партнёра":modal==="staff"?"Добавить специалиста":"Добавить услугу"}</h2>
 {modal==="organization"&&<><label className="field-label">Название<input value={form.name??""} onChange={event=>field("name",event.target.value)} placeholder="Название салона"/></label><label className="field-label">Адрес страницы<input value={form.slug??""} onChange={event=>field("slug",event.target.value)} placeholder="salon-luna"/></label><label className="field-label">Город<input value={form.city??""} onChange={event=>field("city",event.target.value)} placeholder="Новосибирск"/></label><label className="field-label">Адрес<input value={form.address??""} onChange={event=>field("address",event.target.value)} placeholder="Улица, дом"/></label><label className="field-label">Направление<input value={form.category??""} onChange={event=>field("category",event.target.value)} placeholder="Маникюр и педикюр"/></label></>}
 {modal!=="organization"&&<label className="field-label">Партнёр<select value={form.organizationId??""} onChange={event=>field("organizationId",event.target.value)}>{(data?.organizations??[]).map((org:Dict)=><option value={org.id} key={org.id}>{org.name}</option>)}</select></label>}
 {modal==="staff"&&<><label className="field-label">Имя специалиста<input value={form.name??""} onChange={event=>field("name",event.target.value)} placeholder="Анна Соколова"/></label><label className="field-label">Специализация<input value={form.role??""} onChange={event=>field("role",event.target.value)} placeholder="Мастер маникюра"/></label><div className="field-row"><label className="field-label">Начало<input type="time" value={form.workStart??"10:00"} onChange={event=>field("workStart",event.target.value)}/></label><label className="field-label">Окончание<input type="time" value={form.workEnd??"19:00"} onChange={event=>field("workEnd",event.target.value)}/></label></div></>}
 {modal==="service"&&<><label className="field-label">Название услуги<input value={form.name??""} onChange={event=>field("name",event.target.value)} placeholder="Маникюр с покрытием"/></label><div className="field-row"><label className="field-label">Стоимость, ₽<input type="number" min="0" value={form.price??""} onChange={event=>field("price",event.target.value)}/></label><label className="field-label">Длительность, мин<input type="number" min="15" step="15" value={form.duration??60} onChange={event=>field("duration",event.target.value)}/></label></div></>}
 {error&&<p className="error-text">{error}</p>}<button className="button button-dark button-large modal-submit" disabled={busy} onClick={()=>send(modal==="organization"?"add-organization":modal==="staff"?"add-staff":"add-service",form)}>{busy?"Сохраняем…":"Сохранить"}</button></div></div>}</main>
}

function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{hint}</small></article>}
function AppointmentTable({list,onStatus}:{list:Dict[];onStatus:(item:Dict,status:string)=>void}){if(!list.length)return <div className="empty-state"><span>◌</span><h3>Записей пока нет</h3><p>Когда клиенты начнут записываться, вы увидите их здесь.</p></div>;return <div className="table-wrap"><table className="appointments-table"><thead><tr><th>Клиент</th><th>Услуга</th><th>Специалист</th><th>Дата и время</th><th>Стоимость</th><th>Статус</th></tr></thead><tbody>{list.map(item=><tr key={item.id}><td><strong>{item.customer_name}</strong><span>{item.customer_phone}</span></td><td><strong>{item.service_name}</strong><span>{item.organization_name}</span></td><td>{item.staff_name}</td><td>{new Date(`${item.appointment_date}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"short"})}<span>{item.appointment_time}</span></td><td>{rub(item.price)}</td><td><select className={`status status-${item.status}`} value={item.status} onChange={event=>onStatus(item,event.target.value)}>{Object.entries(statuses).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></td></tr>)}</tbody></table></div>}
