"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";

type Dict=Record<string,any>;
const rub=(value:number)=>`${new Intl.NumberFormat("ru-RU").format(value)} ₽`;
const statuses:Record<string,string>={confirmed:"Подтверждена",completed:"Завершена",cancelled:"Отменена",no_show:"Неявка"};
const menu=[{id:"overview",label:"Обзор",icon:"◫"},{id:"appointments",label:"Записи",icon:"◷"},{id:"partners",label:"Партнёры",icon:"◉"},{id:"staff",label:"Специалисты",icon:"♧"},{id:"services",label:"Услуги",icon:"✧"},{id:"accounts",label:"Доступы",icon:"♙",ownerOnly:true},{id:"settings",label:"Уведомления",icon:"♧"},{id:"integration",label:"Bloom Club",icon:"✿"}];

export default function Dashboard(){
 const[tab,setTab]=useState("overview"),[data,setData]=useState<Dict|null>(null),[organization,setOrganization]=useState(""),[modal,setModal]=useState(""),[form,setForm]=useState<Dict>({}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState("");
 const load=useCallback(()=>{fetch(`/api/booking?kind=dashboard${organization?`&organizationId=${encodeURIComponent(organization)}`:""}`).then(async response=>{const result=await response.json();if(!response.ok)throw Error(result.error);setData(result)}).catch(reason=>setError(reason.message))},[organization]);
 useEffect(load,[load]);
 const metrics=useMemo(()=>{const list=data?.appointments??[],active=list.filter((item:Dict)=>item.status!=="cancelled"),today=new Date().toISOString().slice(0,10);return{total:active.length,today:active.filter((item:Dict)=>item.appointment_date===today).length,revenue:active.reduce((sum:number,item:Dict)=>sum+Number(item.price),0),partners:(data?.organizations??[]).length}},[data]);
 async function send(action:string,values:Dict){setBusy(true);setError("");try{const response=await fetch("/api/booking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...values})});const result=await response.json();if(!response.ok)throw Error(result.error);setModal("");setForm({});load()}catch(reason){setError(reason instanceof Error?reason.message:"Ошибка сохранения")}finally{setBusy(false)}}
 function field(key:string,value:any){setForm({...form,[key]:value})}
 async function copy(value:string,key:string){try{await navigator.clipboard.writeText(value);setCopied(key);window.setTimeout(()=>setCopied(""),2200)}catch{setError("Не удалось скопировать ссылку.")}}
 const list=data?.appointments??[],isOwner=data?.user?.role==="owner",visibleMenu=menu.filter(item=>!item.ownerOnly||isOwner),origin=typeof window!=="undefined"?window.location.origin:"";
 return <main className="dashboard"><aside className="sidebar"><Link href="/" className="brand"><span className="brand-mark">✿</span> bloom<span>online</span></Link><div className="sidebar-label">УПРАВЛЕНИЕ</div><nav className="side-menu">{visibleMenu.map(item=><button onClick={()=>setTab(item.id)} className={tab===item.id?"active":""} key={item.id}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-bottom"><div className="avatar">{data?.user?.name?.[0]??"B"}</div><div><strong>{data?.user?.name??"Загрузка"}</strong><span>{isOwner?"Владелец":"Партнёр"}</span></div></div></aside><section className="dashboard-main"><header className="dashboard-top"><span className="eyebrow">BLOOM ONLINE / {menu.find(item=>item.id===tab)?.label.toUpperCase()}</span><select value={organization} onChange={event=>setOrganization(event.target.value)}>{isOwner&&<option value="">Все партнёры</option>}{(data?.organizations??[]).map((org:Dict)=><option key={org.id} value={org.id}>{org.name}</option>)}</select></header><div className="dashboard-body">
 {tab==="overview"&&<><div className="dashboard-heading"><div><div className="eyebrow">ДОБРО ПОЖАЛОВАТЬ</div><h1 className="dashboard-title">Обзор</h1></div>{isOwner&&<button className="button button-dark" onClick={()=>setModal("organization")}>+ Добавить партнёра</button>}</div><div className="metrics-grid"><Metric label="Все записи" value={String(metrics.total)} hint="За всё время"/><Metric label="Записи сегодня" value={String(metrics.today)} hint="На текущую дату"/><Metric label="Сумма записей" value={rub(metrics.revenue)} hint="Без отменённых"/><Metric label="Из Bloom Club" value={String(list.filter((item:Dict)=>item.source==="bloom-club").length)} hint="Привлечено клубом"/></div><div className="block-heading"><h2>Последние записи</h2><button onClick={()=>setTab("appointments")}>Смотреть все →</button></div><AppointmentTable list={list.slice(0,7)} onStatus={(item,status)=>send("update-status",{id:item.id,status})}/></>}
 {tab==="appointments"&&<><div className="dashboard-heading"><div><div className="eyebrow">ЖУРНАЛ ВИЗИТОВ</div><h1 className="dashboard-title">Записи</h1></div><span className="muted">{list.length} всего</span></div><AppointmentTable list={list} onStatus={(item,status)=>send("update-status",{id:item.id,status})}/></>}
 {tab==="partners"&&<><div className="dashboard-heading"><div><div className="eyebrow">ВАША ЭКОСИСТЕМА</div><h1 className="dashboard-title">Партнёры</h1></div>{isOwner&&<button className="button button-dark" onClick={()=>setModal("organization")}>+ Добавить партнёра</button>}</div><div className="admin-card-grid">{(data?.organizations??[]).map((org:Dict)=><article className="admin-card" key={org.id}><div className="admin-card-badge" style={{background:org.color}}>{org.name.split(" ").map((word:string)=>word[0]).join("")}</div><h3>{org.name}</h3><p>{org.category} · {org.city}</p><span className="muted">{org.address}</span><Link href={`/book/${org.slug}`} target="_blank">Страница записи ↗</Link></article>)}</div></>}
 {tab==="staff"&&<><div className="dashboard-heading"><div><div className="eyebrow">КОМАНДА ПАРТНЁРОВ</div><h1 className="dashboard-title">Специалисты</h1></div><button className="button button-dark" onClick={()=>{setForm({organizationId:organization||data?.organizations?.[0]?.id,workStart:"10:00",workEnd:"19:00"});setModal("staff")}}>+ Добавить мастера</button></div><div className="admin-card-grid">{(data?.staff??[]).map((item:Dict)=><article className="admin-card staff-card" key={item.id}><div className="avatar avatar-large">{item.name[0]}</div><h3>{item.name}</h3><p>{item.role}</p><span className="muted">{data?.organizations.find((org:Dict)=>org.id===item.organization_id)?.name}</span><div className="staff-hours">◷ {item.work_start} — {item.work_end}</div></article>)}</div></>}
 {tab==="services"&&<><div className="dashboard-heading"><div><div className="eyebrow">ПРАЙС-ЛИСТ</div><h1 className="dashboard-title">Услуги</h1></div><button className="button button-dark" onClick={()=>{setForm({organizationId:organization||data?.organizations?.[0]?.id,duration:60});setModal("service")}}>+ Добавить услугу</button></div><div className="service-table">{(data?.services??[]).map((item:Dict)=><div className="service-row" key={item.id}><div><strong>{item.name}</strong><span>{data?.organizations.find((org:Dict)=>org.id===item.organization_id)?.name}</span></div><span>{item.duration} мин</span><strong>{rub(item.price)}</strong></div>)}</div></>}
 {tab==="accounts"&&isOwner&&<><div className="dashboard-heading"><div><div className="eyebrow">РОЛИ И РАЗРЕШЕНИЯ</div><h1 className="dashboard-title">Доступы партнёров</h1></div><button className="button button-dark" onClick={()=>{setForm({organizationId:organization||data?.organizations?.[0]?.id});setModal("account")}}>+ Выдать доступ</button></div><div className="notice-card"><strong>Безопасный вход по email</strong><p>Партнёр входит через подтверждённый аккаунт и видит только свою организацию, специалистов, услуги и записи. Для доступа извне потребуется отдельно открыть сайт выбранным пользователям.</p></div><div className="account-list">{(data?.accounts??[]).map((account:Dict)=><article className="account-row" key={account.id}><div className="avatar">{(account.display_name||account.email)[0].toUpperCase()}</div><div><strong>{account.display_name||account.email}</strong><span>{account.email}</span></div><span className="account-org">{account.role==="owner"?"Все организации":account.organization_name}</span><span className={`role-badge${account.active?"":" role-disabled"}`}>{account.role==="owner"?"Владелец":account.active?"Партнёр":"Отключён"}</span>{account.role!=="owner"&&<button className="text-action" onClick={()=>send("update-account",{id:account.id,active:!account.active})}>{account.active?"Отключить":"Включить"}</button>}</article>)}</div></>}
 {tab==="settings"&&<><div className="dashboard-heading"><div><div className="eyebrow">СВЯЗЬ С КЛИЕНТАМИ</div><h1 className="dashboard-title">Telegram-уведомления</h1></div><span className={`integration-status${data?.telegramConfigured?" enabled":""}`}>{data?.telegramConfigured?"Бот подключён":"Ожидает токен бота"}</span></div>{!data?.telegramConfigured&&<div className="notice-card"><strong>Что нужно для подключения</strong><p>Создайте Telegram-бота через @BotFather и добавьте его токен в настройках сервера как TELEGRAM_BOT_TOKEN. Затем укажите chat ID партнёра ниже.</p></div>}<div className="settings-list">{(data?.organizations??[]).map((org:Dict)=><article className="settings-card" key={org.id}><div><h3>{org.name}</h3><p>{org.telegram_chat_id?`Chat ID: ${org.telegram_chat_id}`:"Telegram chat ID не указан"}</p><span className={`integration-status${org.notifications_enabled&&org.telegram_chat_id?" enabled":""}`}>{org.notifications_enabled&&org.telegram_chat_id?"Уведомления включены":"Уведомления выключены"}</span></div><div className="settings-actions"><button className="button button-outline" onClick={()=>{setForm({organizationId:org.id,telegramChatId:org.telegram_chat_id??"",notificationsEnabled:Boolean(org.notifications_enabled),bloomDiscountPercent:org.bloom_discount_percent??0,timezone:org.timezone??"Asia/Novosibirsk"});setModal("settings")}}>Настроить</button>{org.notifications_enabled&&org.telegram_chat_id&&<button className="text-action" onClick={()=>send("test-telegram",{organizationId:org.id})}>Отправить тест</button>}</div></article>)}</div><div className="block-heading"><h2>Последние уведомления</h2></div><div className="notification-list">{(data?.notifications??[]).length?((data?.notifications??[]) as Dict[]).map(item=><div className="notification-row" key={item.id}><span className={`event-dot event-${item.status}`}/><div><strong>{item.organization_name}</strong><span>{item.detail}</span></div><small>{new Date(item.created_at).toLocaleString("ru-RU")}</small></div>):<div className="empty-state"><span>◌</span><h3>Уведомлений пока нет</h3><p>История отправок появится после первых записей.</p></div>}</div></>}
 {tab==="integration"&&<><div className="dashboard-heading"><div><div className="eyebrow">СВЯЗЬ С ЭКОСИСТЕМОЙ</div><h1 className="dashboard-title">Bloom Club</h1></div></div><div className="notice-card"><strong>Отдельная ссылка для каждого партнёра</strong><p>Разместите ссылку в карточке партнёра Bloom Club. Записи с таких ссылок автоматически отмечаются как приведённые клубом.</p></div><div className="integration-list">{(data?.organizations??[]).map((org:Dict)=>{const link=`${origin}/book/${org.slug}?source=bloom-club`,snippet=`<a href="${link}" target="_blank" rel="noopener">Записаться онлайн</a>`;return <article className="integration-card" key={org.id}><div className="integration-card-head"><div className="admin-card-badge" style={{background:org.color}}>{org.name.split(" ").map((word:string)=>word[0]).join("")}</div><div><h3>{org.name}</h3><span>{org.city} · {org.category}</span></div></div><label className="field-label">Ссылка для Bloom Club<div className="copy-field"><input readOnly value={link}/><button onClick={()=>copy(link,org.id)}>{copied===org.id?"Готово":"Копировать"}</button></div></label><label className="field-label">Кнопка для сайта<div className="copy-field"><input readOnly value={snippet}/><button onClick={()=>copy(snippet,`html-${org.id}`)}>{copied===`html-${org.id}`?"Готово":"Копировать"}</button></div></label>{Number(org.bloom_discount_percent)>0&&<div className="discount-note">Привилегия клуба: −{org.bloom_discount_percent}%</div>}</article>})}</div><div className="notice-card domain-note"><strong>Собственный домен</strong><p>После подключения домена ссылки автоматически будут формироваться с новым адресом. Для подключения потребуется выбранный домен и настройка DNS.</p></div></>}
 {error&&<p className="error-text">{error}</p>}</div></section>
 {modal&&<div className="modal-backdrop" onClick={event=>{if(event.target===event.currentTarget)setModal("")}}><div className="modal"><button className="modal-close" onClick={()=>setModal("")}>×</button><div className="eyebrow">{modal==="settings"?"НАСТРОЙКИ ПАРТНЁРА":"НОВАЯ ЗАПИСЬ В СИСТЕМЕ"}</div><h2>{modal==="organization"?"Добавить партнёра":modal==="staff"?"Добавить специалиста":modal==="account"?"Выдать доступ":modal==="settings"?"Уведомления и привилегии":"Добавить услугу"}</h2>
 {modal==="organization"&&<><label className="field-label">Название<input value={form.name??""} onChange={event=>field("name",event.target.value)} placeholder="Название салона"/></label><label className="field-label">Адрес страницы<input value={form.slug??""} onChange={event=>field("slug",event.target.value)} placeholder="salon-luna"/></label><label className="field-label">Город<input value={form.city??""} onChange={event=>field("city",event.target.value)} placeholder="Новосибирск"/></label><label className="field-label">Адрес<input value={form.address??""} onChange={event=>field("address",event.target.value)} placeholder="Улица, дом"/></label><label className="field-label">Направление<input value={form.category??""} onChange={event=>field("category",event.target.value)} placeholder="Маникюр и педикюр"/></label></>}
 {modal!=="organization"&&modal!=="settings"&&<label className="field-label">Партнёр<select value={form.organizationId??""} onChange={event=>field("organizationId",event.target.value)}>{(data?.organizations??[]).map((org:Dict)=><option value={org.id} key={org.id}>{org.name}</option>)}</select></label>}
 {modal==="staff"&&<><label className="field-label">Имя специалиста<input value={form.name??""} onChange={event=>field("name",event.target.value)} placeholder="Анна Соколова"/></label><label className="field-label">Специализация<input value={form.role??""} onChange={event=>field("role",event.target.value)} placeholder="Мастер маникюра"/></label><div className="field-row"><label className="field-label">Начало<input type="time" value={form.workStart??"10:00"} onChange={event=>field("workStart",event.target.value)}/></label><label className="field-label">Окончание<input type="time" value={form.workEnd??"19:00"} onChange={event=>field("workEnd",event.target.value)}/></label></div></>}
 {modal==="service"&&<><label className="field-label">Название услуги<input value={form.name??""} onChange={event=>field("name",event.target.value)} placeholder="Маникюр с покрытием"/></label><div className="field-row"><label className="field-label">Стоимость, ₽<input type="number" min="0" value={form.price??""} onChange={event=>field("price",event.target.value)}/></label><label className="field-label">Длительность, мин<input type="number" min="15" step="15" value={form.duration??60} onChange={event=>field("duration",event.target.value)}/></label></div></>}
 {modal==="account"&&<><label className="field-label">Email партнёра<input type="email" value={form.email??""} onChange={event=>field("email",event.target.value)} placeholder="partner@example.ru"/></label><label className="field-label">Имя для отображения<input value={form.displayName??""} onChange={event=>field("displayName",event.target.value)} placeholder="Анна Морозова"/></label><p className="consent">Доступ предоставляется только к выбранной организации.</p></>}
 {modal==="settings"&&<><label className="field-label">Telegram chat ID<input value={form.telegramChatId??""} onChange={event=>field("telegramChatId",event.target.value)} placeholder="123456789 или -1001234567890"/></label><label className="toggle-label"><input type="checkbox" checked={Boolean(form.notificationsEnabled)} onChange={event=>field("notificationsEnabled",event.target.checked)}/> Отправлять уведомления о новых записях</label><label className="field-label">Привилегия Bloom Club, %<input type="number" min="0" max="90" value={form.bloomDiscountPercent??0} onChange={event=>field("bloomDiscountPercent",event.target.value)}/></label><label className="field-label">Часовой пояс<select value={form.timezone??"Asia/Novosibirsk"} onChange={event=>field("timezone",event.target.value)}><option value="Asia/Novosibirsk">Новосибирск</option><option value="Europe/Moscow">Москва</option><option value="Asia/Yekaterinburg">Екатеринбург</option></select></label></>}
 {error&&<p className="error-text">{error}</p>}<button className="button button-dark button-large modal-submit" disabled={busy} onClick={()=>send(modal==="organization"?"add-organization":modal==="staff"?"add-staff":modal==="account"?"add-account":modal==="settings"?"update-organization":"add-service",form)}>{busy?"Сохраняем…":"Сохранить"}</button></div></div>}</main>
}

function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{hint}</small></article>}
function AppointmentTable({list,onStatus}:{list:Dict[];onStatus:(item:Dict,status:string)=>void}){if(!list.length)return <div className="empty-state"><span>◌</span><h3>Записей пока нет</h3><p>Когда клиенты начнут записываться, вы увидите их здесь.</p></div>;return <div className="table-wrap"><table className="appointments-table"><thead><tr><th>Клиент</th><th>Услуга</th><th>Специалист</th><th>Дата и время</th><th>Стоимость</th><th>Статус</th></tr></thead><tbody>{list.map(item=><tr key={item.id}><td><strong>{item.customer_name}</strong><span>{item.customer_phone}</span></td><td><strong>{item.service_name}</strong><span>{item.organization_name}</span></td><td>{item.staff_name}</td><td>{new Date(`${item.appointment_date}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"short"})}<span>{item.appointment_time}</span></td><td>{rub(item.price)}</td><td><select className={`status status-${item.status}`} value={item.status} onChange={event=>onStatus(item,event.target.value)}>{Object.entries(statuses).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></td></tr>)}</tbody></table></div>}
