"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Dict=Record<string,any>;
const rub=(value:number)=>`${new Intl.NumberFormat("ru-RU").format(value)} ₽`;
function makeDates(){return Array.from({length:14},(_,index)=>{const date=new Date();date.setDate(date.getDate()+index);return{value:`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`,day:new Intl.DateTimeFormat("ru-RU",{weekday:"short"}).format(date),number:date.getDate(),month:new Intl.DateTimeFormat("ru-RU",{month:"short"}).format(date)}})}

export default function BookingFlow({slug}:{slug:string}){
 const[info,setInfo]=useState<Dict|null>(null),[step,setStep]=useState(1),[service,setService]=useState<Dict|null>(null),[member,setMember]=useState<Dict|null>(null),[date,setDate]=useState(""),[time,setTime]=useState(""),[slots,setSlots]=useState<string[]>([]),[name,setName]=useState(""),[phone,setPhone]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[confirmed,setConfirmed]=useState(false),[source,setSource]=useState("direct"),[result,setResult]=useState<Dict|null>(null),[consent,setConsent]=useState(false),[website,setWebsite]=useState("");
 const dates=useMemo(makeDates,[]);
 useEffect(()=>{fetch(`/api/booking?kind=organization&slug=${encodeURIComponent(slug)}`).then(async(response)=>{const data=await response.json();if(!response.ok)throw Error(data.error);setInfo(data)}).catch(reason=>setError(reason.message))},[slug]);
 useEffect(()=>{const value=new URLSearchParams(window.location.search).get("source");if(value==="bloom-club")setSource("bloom-club")},[]);
 useEffect(()=>{if(!service||!member||!date)return;setBusy(true);setError("");fetch(`/api/booking?kind=slots&serviceId=${service.id}&staffId=${member.id}&date=${date}`).then(async(response)=>{const data=await response.json();if(!response.ok)throw Error(data.error);setSlots(data.slots??[])}).catch(reason=>setError(reason.message)).finally(()=>setBusy(false))},[service,member,date]);
 async function submit(){setBusy(true);setError("");try{const response=await fetch("/api/booking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"book",serviceId:service?.id,staffId:member?.id,date,time,customerName:name,customerPhone:phone,source,website})});const data=await response.json();if(!response.ok)throw Error(data.error);setResult(data);setConfirmed(true)}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось создать запись")}finally{setBusy(false)}}
 if(!info)return <main className="booking-shell"><Link href="/" className="brand"><span className="brand-mark">✿</span> bloom<span>online</span></Link><p className="muted">{error||"Подготавливаем страницу записи…"}</p></main>;
 const org=info.organization;
 if(confirmed)return <main className="booking-shell confirmation"><Link href="/" className="brand"><span className="brand-mark">✿</span> bloom<span>online</span></Link><div className="confirm-icon">✓</div><div className="eyebrow">ВСТРЕЧА ЗАПЛАНИРОВАНА</div><h1 className="booking-title">Вы записаны</h1><p>Будем ждать вас в {org.name}.</p><div className="summary-box"><div><span>Услуга</span><strong>{service?.name}</strong></div><div><span>Специалист</span><strong>{member?.name}</strong></div><div><span>Дата и время</span><strong>{new Date(`${date}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"long"})}, {time}</strong></div><div><span>Адрес</span><strong>{org.address}</strong></div>{Number(result?.discount)>0&&<div><span>Скидка Bloom Club</span><strong>−{rub(result?.discount??0)}</strong></div>}<div><span>Стоимость</span><strong>{rub(result?.price??service?.price??0)}</strong></div></div>{result?.id&&result?.token&&<Link href={`/appointment/${result.id}?token=${encodeURIComponent(result.token)}`} className="button button-outline button-large manage-link">Управление записью</Link>}<Link href="/" className="button button-dark button-large">На главную</Link></main>;
 return <main className="booking-shell"><header className="booking-header"><Link href="/" className="brand"><span className="brand-mark">✿</span> bloom<span>online</span></Link><Link href="/#partners" className="muted">← Все партнёры</Link></header><div className="booking-layout"><aside className="booking-side"><div className="booking-monogram" style={{backgroundColor:org.color}}>{org.name.split(" ").map((word:string)=>word[0]).join("")}</div><div className="eyebrow">ПАРТНЁР BLOOM CLUB</div><h1 className="booking-title">{org.name}</h1><p className="muted">{org.category}</p>{source==="bloom-club"&&Number(org.bloom_discount_percent)>0&&<div className="member-perk">✿ Привилегия Bloom Club: −{org.bloom_discount_percent}% при подтверждении участия</div>}<div className="side-address">◉ &nbsp;{org.city}, {org.address}</div><p className="side-description">{org.description}</p></aside><section className="booking-content"><div className="step-indicator">{[1,2,3,4].map(item=><span className={item<=step?"step-active":""} key={item}>{String(item).padStart(2,"0")}</span>)}</div>
 {step===1&&<><div className="eyebrow">ШАГ 01</div><h2>Выберите услугу</h2><div className="option-list">{info.services.map((item:Dict)=><button className={`option-card${service?.id===item.id?" selected":""}`} onClick={()=>{setService(item);setStep(2)}} key={item.id}><div><strong>{item.name}</strong><span>{item.duration} мин</span></div><strong>{rub(item.price)}</strong></button>)}</div>{!info.services.length&&<p className="muted">Партнёр пока не добавил услуги.</p>}</>}
 {step===2&&<><div className="eyebrow">ШАГ 02</div><h2>Выберите специалиста</h2><div className="option-list">{info.staff.filter((item:Dict)=>{const links=(info.staffServices??[]).filter((link:Dict)=>link.staff_id===item.id);return!links.length||links.some((link:Dict)=>link.service_id===service?.id)}).map((item:Dict)=><button className={`option-card${member?.id===item.id?" selected":""}`} onClick={()=>{setMember(item);setStep(3)}} key={item.id}><div className="staff-option"><span className="avatar">{item.name[0]}</span><div><strong>{item.name}</strong><span>{item.role}</span></div></div><span>→</span></button>)}</div><button className="back-button" onClick={()=>setStep(1)}>← Назад к услугам</button></>}
 {step===3&&<><div className="eyebrow">ШАГ 03</div><h2>Дата и время</h2><div className="date-strip">{dates.map(item=><button className={`date-item${date===item.value?" selected":""}`} onClick={()=>{setDate(item.value);setTime("")}} key={item.value}><span>{item.day}</span><strong>{item.number}</strong><span>{item.month}</span></button>)}</div>{date&&<><h3 className="time-heading">Свободное время</h3>{busy?<p className="muted">Проверяем расписание…</p>:<div className="time-grid">{slots.map(slot=><button className={`time-chip${time===slot?" selected":""}`} onClick={()=>setTime(slot)} key={slot}>{slot}</button>)}</div>}{!busy&&!slots.length&&<p className="muted">На эту дату свободных интервалов нет.</p>}</>}{time&&<button className="button button-dark button-large next-button" onClick={()=>setStep(4)}>Продолжить →</button>}<button className="back-button" onClick={()=>setStep(2)}>← Назад к специалистам</button></>}
 {step===4&&<><div className="eyebrow">ШАГ 04</div><h2>Ваши данные</h2><div className="summary-compact"><strong>{service?.name}</strong><span>{member?.name} · {new Date(`${date}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"long"})}, {time}</span>{source==="bloom-club"&&Number(org.bloom_discount_percent)>0?<><span className="price-before">{rub(service?.price??0)}</span><strong>{rub((service?.price??0)-Math.floor((service?.price??0)*Number(org.bloom_discount_percent)/100))} · скидка {org.bloom_discount_percent}%</strong></>:<strong>{rub(service?.price??0)}</strong>}</div><label className="field-label">Ваше имя<input value={name} onChange={event=>setName(event.target.value)} placeholder="Например, Анна" autoComplete="name"/></label><label className="field-label">Номер телефона<input value={phone} onChange={event=>setPhone(event.target.value)} placeholder="+7 999 123-45-67" autoComplete="tel" type="tel"/></label><div className="honeypot" aria-hidden="true"><input value={website} onChange={event=>setWebsite(event.target.value)} tabIndex={-1} autoComplete="off"/></div><label className="consent-check"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/> Я соглашаюсь на обработку персональных данных для оформления записи.</label><button className="button button-dark button-large next-button" disabled={busy||!consent||name.trim().length<2||phone.replace(/\D/g,"").length<10} onClick={submit}>{busy?"Создаём запись…":"Подтвердить запись →"}</button><button className="back-button" onClick={()=>setStep(3)}>← Изменить время</button></>}
 {error&&<p className="error-text">{error}</p>}</section></div></main>
}
